# Generated by Django 2.2.6 on 2021-04-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20210402_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='Заполните поле.', verbose_name='Текст'),
        ),
    ]
