# Generated by Django 2.2.6 on 2021-04-09 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
